version: "3.9"

services:
  paper:
    image: itzg/minecraft-server:latest
    container_name: paper
    networks:
      - coolify
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - TYPE=PAPER
      - VERSION=1.21.4
      - MEMORY=4G
      - TZ=America/New_York
    volumes:
      - ./data:/data
    restart: unless-stopped

networks:
  coolify:
    external: true
