version: "3.9"

services:
  bed-rock:
    image: itzg/minecraft-server:latest
    container_name: bed-rock
    networks:
      - coolify
    ports:
      - "19132:19132"
    environment:
      - EULA=TRUE
      - VERSION=1.21.4
      - MEMORY=4G
      - TZ=America/New_York
    volumes:
      - ./data:/data
    restart: unless-stopped

networks:
  coolify:
    external: true
